### ISSUE TITLE
Activity view items order/visibility

### ISSUE THREAD

**Issue by ftorto** [Runalyze/Runalyze#2274] opened 2018-01-08 09:53 UTC
In **Activity view** settings, we have an option: **show map first** which is great.

Can we go a bit more customizable and be able to choose the **display order** and **visibility** of any item of the activity view:

- composite data
- Laps
- Running dynamics
- Miscellaneous

My current need is to hide **Laps** information because I don't use this information. But the **running dynamics** and **misc** are interesting to me

Thanks

**Comment by laufhannes** [comment] 2018-01-08 09:57
This is a duplicate of #1548 and will not happen until we achieve a complete re-design of the activity view. (And I'm not sure whether we'll keep and enhance customization options or whether we'll drop them completely.)

**Closed by laufhannes** 2018-01-08 09:57 UTC
Labels: duplicate
