### ISSUE TITLE
Atomatic detection of pauses based on GPS data

### ISSUE THREAD

**Issue by mlegner** [Runalyze/Runalyze#2091] opened 2017-03-07 10:03 UTC
For hikes and cycle tours I usually do not create pauses with my Garmin watch. However, I do have some pauses where I am stationary for some time.
It is already possible to detect pauses on import. It would be a great additional feature if pauses could be detected based on the GPS data (when one is stationary for a specific amount of time).

**Comment by laufhannes** [comment] 2017-03-07 10:09
I'll close this as duplicate of #913.

The current option to detect pauses is only used for tcx files, I think. But it's a complex topic, as a lot of file formats do not really have an option to mark such pauses and the automatic detection fails and produces a lot of false positives. So, this will be part of a bigger refactoring and it's somehow related to #1576.

**Closed by laufhannes** 2017-03-07 10:09 UTC
Labels: duplicate
