### ISSUE TITLE
Activity editor not fully modal

### ISSUE THREAD

**Issue by HeikoTietze** [Runalyze/Runalyze#2149] opened 2017-05-06 11:52 UTC
When clicking unintentionally not within the activity editor the window disappears but seems to be still active. The dropdown menu with edit doesn't work unless the page is reloaded.

Awesome program, anyway. Thanks a lot for your effort.

**Comment by mipapo** [comment] 2017-05-06 12:13
@HeikoTietze  I cannot reproduce any of your problems. Could you record your problems?

**Comment by HeikoTietze** [comment] 2017-05-06 12:36
Tried to reproduce but now the window disappear without any follow-up issue. Running FF53 on Linux.

**Comment by mipapo** [comment] 2017-05-06 12:40
So we can close the issue?

**Comment by HeikoTietze** [comment] 2017-05-06 12:43
Would keep it open for a while to see if others confirm the issue.

**Comment by mipapo** [comment] 2017-05-06 12:44
That would be such an obvious issue. Anyone can still comment on this issue. I will close it.

**Closed by mipapo** 2017-05-06 12:44 UTC
