### ISSUE TITLE
VDOT by elevation: use exact gradient from gps data

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#791] opened 2014-08-20 18:44 UTC
**Reported by hugo3673 on 19 Nov 43413731 19:33 UTC**
siehe http://www.laufen-in-siegen.de/index.html?./html/laelles_3.html

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1504

**Comment by laufhannes** [comment] 2015-11-09 08:38
Duplicate of #1573.

**Closed by laufhannes** 2015-11-09 08:38 UTC
Labels: duplicate
