### ISSUE TITLE
Robert Bock (CPP) prognosis calculator wrong values

### ISSUE THREAD

**Issue by rretsiem** [Runalyze/Runalyze#1616] opened 2015-12-04 13:38 UTC
The prognosis calculator for the Robert Bock (CPP) model calculates strange results. All other models seem to work correctly. (Online version hosted by you)

<img width="808" alt="robertbock_cpp_prognosis" src="https://cloud.githubusercontent.com/assets/248836/11590979/8a3fe58a-9a94-11e5-84f2-a3d65064f548.png">

**Comment by laufhannes** [comment] 2015-12-04 13:45
Duplicate of #1258.

**Closed by laufhannes** 2015-12-04 13:45 UTC
Labels: duplicate
