### ISSUE TITLE
Session_ID problem (Integrity constraint violation)

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1348] opened 2015-04-02 10:49 UTC
````
Integrity constraint violation: 1062 Duplicate entry '84mflhea7e1a2udetn3' for key 'session_id'' in inc/system/class.PDOforRunalyze.php:260
#0 /var/www/runalyze/user/inc/system/class.PDOforRunalyze.php(260): PDO->query('UPDATE `runalyz...')
#1 /var/www/runalyze/user/inc/system/class.PDOforRunalyze.php(130): PDOforRunalyze->query('UPDATE `runalyz...')
#2 /var/www/runalyze/user/inc/system/class.PDOforRunalyze.php(108): PDOforRunalyze->updateWhere('account', '`id`="2" LIMIT ...', Array, Array)
#3 /var/www/runalyze/user/inc/system/class.SessionAccountHandler.php(262): PDOforRunalyze->update('account', '2', Array, Array)
#4 /var/www/runalyze/user/inc/system/class.SessionAccountHandler.php(245): SessionAccountHandler->setSessionToDatabase()
#5 /var/www/runalyze/user/inc/system/class.SessionAccountHandler.php(185): SessionAccountHandler->setSession()
````

Steps to reproduce: Login in as a user. Logout. Login as another user

**Comment by laufhannes** [comment] 2015-04-02 11:21
Duplicate of #1162.

**Closed by laufhannes** 2015-04-02 11:21 UTC
Labels: bug
